import pandas as pd


def get_rich_demo_vendor_inventory_df():
    """Return a richer fictional vendor inventory for demos and portfolio walkthroughs."""
    return pd.DataFrame([
        {
            "Vendor": "FinAssist AI",
            "System": "AI-powered loan screening platform",
            "Data_Type": "Financial Data",
            "Business_Criticality": "High",
            "Has_SOC2": "No",
            "Has_MFA": "No",
            "Encryption": "Unknown",
            "Incident_Response_Plan": "No",
            "Known_Vulnerability": "Yes",
            "Last_Risk_Review": "2025-09-26",
        },
        {
            "Vendor": "SecureDocs Cloud",
            "System": "Document management platform",
            "Data_Type": "Confidential Data",
            "Business_Criticality": "Medium",
            "Has_SOC2": "Yes",
            "Has_MFA": "Yes",
            "Encryption": "Yes",
            "Incident_Response_Plan": "Yes",
            "Known_Vulnerability": "No",
            "Last_Risk_Review": "2026-03-15",
        },
        {
            "Vendor": "PayFlow Gateway",
            "System": "Payment processing API",
            "Data_Type": "Financial Data",
            "Business_Criticality": "High",
            "Has_SOC2": "Yes",
            "Has_MFA": "No",
            "Encryption": "Yes",
            "Incident_Response_Plan": "No",
            "Known_Vulnerability": "No",
            "Last_Risk_Review": "2025-12-10",
        },
        {
            "Vendor": "PeopleCore HR",
            "System": "Human resources management system",
            "Data_Type": "PII",
            "Business_Criticality": "High",
            "Has_SOC2": "No",
            "Has_MFA": "Yes",
            "Encryption": "Unknown",
            "Incident_Response_Plan": "Yes",
            "Known_Vulnerability": "No",
            "Last_Risk_Review": "2025-08-18",
        },
        {
            "Vendor": "MediClaims Portal",
            "System": "Healthcare claims intake platform",
            "Data_Type": "PHI",
            "Business_Criticality": "High",
            "Has_SOC2": "No",
            "Has_MFA": "No",
            "Encryption": "No",
            "Incident_Response_Plan": "No",
            "Known_Vulnerability": "Yes",
            "Last_Risk_Review": "2025-07-01",
        },
        {
            "Vendor": "MailReach Automation",
            "System": "Marketing email automation",
            "Data_Type": "Customer Emails",
            "Business_Criticality": "Low",
            "Has_SOC2": "No",
            "Has_MFA": "Yes",
            "Encryption": "Yes",
            "Incident_Response_Plan": "No",
            "Known_Vulnerability": "No",
            "Last_Risk_Review": "2026-02-01",
        },
        {
            "Vendor": "CloudVault Backup",
            "System": "Cloud backup and recovery",
            "Data_Type": "Confidential Data",
            "Business_Criticality": "High",
            "Has_SOC2": "Yes",
            "Has_MFA": "Yes",
            "Encryption": "Yes",
            "Incident_Response_Plan": "No",
            "Known_Vulnerability": "No",
            "Last_Risk_Review": "2025-10-20",
        },
        {
            "Vendor": "IDProof Verify",
            "System": "Identity verification service",
            "Data_Type": "PII",
            "Business_Criticality": "Medium",
            "Has_SOC2": "Yes",
            "Has_MFA": "No",
            "Encryption": "Unknown",
            "Incident_Response_Plan": "Yes",
            "Known_Vulnerability": "No",
            "Last_Risk_Review": "2026-01-12",
        },
        {
            "Vendor": "SupportDesk AI",
            "System": "AI customer support chatbot",
            "Data_Type": "Customer Inputs",
            "Business_Criticality": "Medium",
            "Has_SOC2": "No",
            "Has_MFA": "No",
            "Encryption": "Unknown",
            "Incident_Response_Plan": "No",
            "Known_Vulnerability": "No",
            "Last_Risk_Review": "2025-11-05",
        },
        {
            "Vendor": "LegalSign eDocs",
            "System": "Electronic signature platform",
            "Data_Type": "Confidential Data",
            "Business_Criticality": "Medium",
            "Has_SOC2": "Yes",
            "Has_MFA": "Yes",
            "Encryption": "Yes",
            "Incident_Response_Plan": "Yes",
            "Known_Vulnerability": "No",
            "Last_Risk_Review": "2026-04-10",
        },
        {
            "Vendor": "AnalyticsHub BI",
            "System": "Business intelligence dashboard",
            "Data_Type": "Internal Data",
            "Business_Criticality": "Medium",
            "Has_SOC2": "No",
            "Has_MFA": "Yes",
            "Encryption": "Yes",
            "Incident_Response_Plan": "Yes",
            "Known_Vulnerability": "No",
            "Last_Risk_Review": "2026-03-01",
        },
        {
            "Vendor": "LegacyCRM Pro",
            "System": "Customer relationship management",
            "Data_Type": "PII",
            "Business_Criticality": "High",
            "Has_SOC2": "No",
            "Has_MFA": "No",
            "Encryption": "No",
            "Incident_Response_Plan": "No",
            "Known_Vulnerability": "Yes",
            "Last_Risk_Review": "2024-12-15",
        },
        {
            "Vendor": "DevOpsBuild Cloud",
            "System": "CI CD deployment pipeline",
            "Data_Type": "Internal Data",
            "Business_Criticality": "High",
            "Has_SOC2": "Yes",
            "Has_MFA": "Yes",
            "Encryption": "Unknown",
            "Incident_Response_Plan": "No",
            "Known_Vulnerability": "Yes",
            "Last_Risk_Review": "2025-09-01",
        },
        {
            "Vendor": "PublicForms Lite",
            "System": "Public website form builder",
            "Data_Type": "Public Data",
            "Business_Criticality": "Low",
            "Has_SOC2": "Yes",
            "Has_MFA": "Yes",
            "Encryption": "Yes",
            "Incident_Response_Plan": "Yes",
            "Known_Vulnerability": "No",
            "Last_Risk_Review": "2026-05-01",
        },
    ])


def get_invalid_demo_vendor_inventory_df():
    """Return an intentionally invalid CSV sample to test validation behavior."""
    return pd.DataFrame([
        {
            "Vendor": "InvalidVendor One",
            "System": "Test platform",
            "Data_Type": "PII",
            "Business_Criticality": "Urgent",
            "Has_SOC2": "Maybe",
            "Has_MFA": "No",
            "Encryption": "Partial",
            "Incident_Response_Plan": "No",
            "Known_Vulnerability": "Yes",
            "Last_Risk_Review": "05/24/2026",
        },
        {
            "Vendor": "",
            "System": "",
            "Data_Type": "",
            "Business_Criticality": "High",
            "Has_SOC2": "No",
            "Has_MFA": "Maybe",
            "Encryption": "Unknown",
            "Incident_Response_Plan": "Later",
            "Known_Vulnerability": "No",
            "Last_Risk_Review": "2030-01-01",
        },
    ])
